name: Snake Animation 🐍

on:
  schedule:
    - cron: "0 */12 * * *"  # Cada 12 horas
  workflow_dispatch:

jobs:
  generate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Debug git status
        run: |
          git fetch --all
          git branch -a
          git status

      - name: Generate snake animation
        uses: Platane/snk@v3
        with:
          github_user_name: AndresContreras1034
          outputs: |
            dist/github-contribution-grid-snake.svg
            dist/github-contribution-grid-snake-dark.svg?palette=github-dark

      - name: Push to output branch
        uses: crazy-max/ghaction-github-pages@v4
        with:
          target_branch: output
          build_dir: dist
          force_orphan: true
        env:
          GITHUB_TOKEN: ${{ secrets.PAT }}
